import "./globals.css";
import Header from "./components/Header";
import BentoGrid from "./components/BentoGrid";
import Topbar from "./components/Topbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body>
          <Topbar />
          <Header />
          <BentoGrid />
          <main>{children}</main>
          <Footer/>
        </body>
      </html>
    </>
  );
}
