
import "./globals.css";
import Header from "./components/Header";
import BentoGrid from "./components/BentoGrid";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <>
       <html lang="en">
       <body>
      <Header/>
      <BentoGrid/>
      <main>{children}</main>
      </body>
      </html>
      </>
  );
}
